FROM python:3.12-slim

# crear carpeta de trabajo 
WORKDIR /app

# copia de requerimientos 
COPY requirements.txt .

# instalarlos
RUN pip install --no-cache-dir -r requirements.txt

# copiar codigo del proyecto
COPY ./app ./app

# exponer puerto a trabajar 
EXPOSE 5030

# Comandos para ejecutar fastapi
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5030", "--reload"]